[project]
name = "linebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-sqlalchemy>=3.1.1",
    "flask[async]>=3.1.1",
    "psycopg2>=2.9.10",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.41",
]
